version: '3'
services:
  wallet-service:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wallet_db
      - DB_USERNAME=wallet_user
      - DB_PASSWORD=wallet_pass
      - JPA_DDL_AUTO=validate
    command: >
      sh -c "mvn liquibase:update -Ddb.host=$$DB_HOST -Ddb.port=$$DB_PORT -Ddb.name=$$DB_NAME -Ddb.username=$$DB_USERNAME -Ddb.password=$$DB_PASSWORD && 
             java -jar /app.jar"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: