version: '3.8'
services:
  wallet-service:
    build: .
    container_name: wallet-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wallet_db
      - DB_USERNAME=wallet_user
      - DB_PASSWORD=wallet_pass
    depends_on:
      - postgres
    restart: always
    networks:
      - wallet-net

  postgres:
    image: postgres:15
    container_name: postgres_wallet
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - wallet-net

networks:
  wallet-net:
    driver: bridge

volumes:
  postgres-data: